In [1]:
import numpy as np

In [4]:
# 1. np.concatenate()
w1=np.array([12,13,14,15])
print(w1)
print(w1.ndim)
print(w1.shape)
w2=np.array([18,19,20,21,22])
print(w2)
print(w2.ndim)
print(w2.shape)

[12 13 14 15]
1
(4,)
[18 19 20 21 22]
1
(5,)


In [5]:
r1=np.concatenate([w1,w2])
print(r1)
r2=np.concatenate([w2,w1])
print(r2)

[12 13 14 15 18 19 20 21 22]
[18 19 20 21 22 12 13 14 15]


In [7]:
d1=np.array([[1,2,3],[4,5,6]])
d2=np.array([[7,8,9],[10,11,12]])
print(d1)
print(d2)
print(d1.shape,d2.shape)
print(d1.ndim,d2.ndim)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
(2, 3) (2, 3)
2 2


In [8]:
r2=np.concatenate([d1,d2],axis=0) #col wise append
# no new col. are created rather new rows are created
print(r2)
r3=np.concatenate([d1,d2],axis=1)  # row wise append
# no new rows are created rathers columns are created
print(r3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [9]:
#2 np.vstack and np.hstack

z1=np.array([[1,2,3],[4,5,6]])
z2=np.array([[-4,-2,0],[7,9,2]])
print(z1)
print(z1.shape)
print(z2)
print(z2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[-4 -2  0]
 [ 7  9  2]]
(2, 3)


In [11]:
r1=np.hstack([z1,z2])
# no ne rows are created
r2=np.vstack([z1,z2])
# no new columns are created
print(r1)
print(r2)

[[ 1  2  3 -4 -2  0]
 [ 4  5  6  7  9  2]]
[[ 1  2  3]
 [ 4  5  6]
 [-4 -2  0]
 [ 7  9  2]]


In [13]:
# 3 np.hsplit() and np.vsplit()

t=np.arange(1,9)
print(t)
res1=np.hsplit(t,2)
print(res1)

[1 2 3 4 5 6 7 8]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


In [15]:
w1=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(w1)
print(w1.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
(4, 4)


In [16]:
d1=np.hsplit(w1,2)
print(d1)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])]


In [17]:
print(w1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
np.array
r2=np.vsplit(w1,2)
print(r2)

[array([[1, 2, 3, 4],
       [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])]
