In [7]:
import numpy as np

In [8]:
a1=np.array([[1,2],[3,4]])
print(a1.sum())        #1+2+3+4=10
print(a1.sum(axis=1))  # axis=1(row wise), 1+2=3,  3+4=7
print(a1.sum(axis=0))  # axis=0(col wise), 1+3=4,  2+4=6

10
[3 7]
[4 6]


In [44]:
a2=np.arange(10,22).reshape(3,4)
print(a2)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [45]:
a=np.array([1,7,4,3,5,2,2,9,7])
b=np.sum(a)
print(b)

40


In [46]:
a=np.array([[1,7,4],[3,5,2],[2,9,7]])
print(np.extract(a%3==0,a))

[3 9]


In [47]:
a=np.array([[3,7,4],[3,5,2],[2,3,7]])
print(a)
b=np.extract(a>3,a)
print(b)

[[3 7 4]
 [3 5 2]
 [2 3 7]]
[7 4 5 7]


In [12]:
print(a2.sum())        #10+11+12+13....+21=186
print(a2.sum(axis=1))  #row wise = 10+11+12+13=46
print(a2.sum(axis=0))  #col wise= 10+14+18=42

186
[46 62 78]
[42 45 48 51]


In [43]:
# 2 np.max and np.min

m=[[12,13,4],[15,17,16],[18,19,11],[16,22,20]]
w1=np.array(m)
print(w1)
print(w1.shape)
print(w1.ndim)

[[12 13  4]
 [15 17 16]
 [18 19 11]
 [16 22 20]]
(4, 3)
2


In [15]:
# axis 1=row
# axis 0=colum
print(np.min(w1,axis=0)) #[12 13 4]
print(np.min(w1,axis=1)) #[4 15 11 16]
print(np.max(w1,axis=0)) #[18 22 20]
print(np.max(w1,axis=1)) #[13 17 19 22]

[12 13 11]
[12 15 11 16]
[18 22 20]
[14 17 19 22]


In [16]:
# 3 np.argmax() and np.min()

p1=np.array([12,14,7,79,32,45,28,4,17])
print(p1)
print(p1.ndim)

[12 14  7 79 32 45 28  4 17]
1


In [17]:
print(np.max(p1)) #79
print(np.min(p1)) #4

79
4


In [18]:
print(np.argmax(p1)) #3 index of 79
print(np.argmin(p1)) #7 index of 4

3
7


In [20]:
r2=[[16,15,21],[15,16,8],[19,2,18],[9,12,13]]
p2=np.array(r2)
print(p2)

[[16 15 21]
 [15 16  8]
 [19  2 18]
 [ 9 12 13]]


In [22]:
print(np.argmin(p2,axis=0)) #col wise
print(np.argmin(p2,axis=1)) # row wise
print(np.argmax(p2,axis=0))
print(np.argmax(p2,axis=1))

[3 2 1]
[1 2 1 0]
[2 1 0]
[2 1 0 2]


In [24]:
# 4 np.sort()

r1=np.array([34,23,56,12,39])
print(r1)
print(r1.ndim)

[34 23 56 12 39]
1


In [26]:
r2=np.sort(r1)
print(r2)
r2=np.sort(r1)[::-1]
print(r2)

[12 23 34 39 56]
[56 39 34 23 12]


In [29]:
r3=np.array([[11,21,18],[24,35,16],[7,14,3]])
print(r3)
print(r3.ndim)

[[11 21 18]
 [24 35 16]
 [ 7 14  3]]
2


In [30]:
#sort row wise
r4=np.sort(r3,axis=1)
print(r4)
 # sort column wise
r5=np.sort(r3,axis=0)
print(r5)


[[11 18 21]
 [16 24 35]
 [ 3  7 14]]
[[ 7 14  3]
 [11 21 16]
 [24 35 18]]


In [31]:
r6=np.sort(r3)  # default sort order is row wise
print(r6)

[[11 18 21]
 [16 24 35]
 [ 3  7 14]]


In [32]:
# 5  np.where()

p1=np.array([12,14,7,79,32,45,28,4,17])
print(p1)



[12 14  7 79 32 45 28  4 17]


In [34]:
n2=np.where(p1%3==0)
print(n2)
print(p1[np.where(p1%3==0)])

(array([0, 5], dtype=int64),)
[12 45]


In [35]:
print(p1)
print(np.where(p1<20))
print(p1[np.where(p1<20)])

[12 14  7 79 32 45 28  4 17]
(array([0, 1, 2, 7, 8], dtype=int64),)
[12 14  7  4 17]


In [36]:
# using np.where()with 3 parameters

print(p1)
t1=np.where(p1<20,p1+5,p1*2)
# if p1<20 then add 5 to those values else multiply them by 2 
print(t1)
t2=np.where(p1%2==0,p1+10,p1-7)
# if p1%2==0 then add 10 to those values else subtract7 from them
print(t2)

[12 14  7 79 32 45 28  4 17]
[ 17  19  12 158  64  90  56   9  22]
[22 24  0 72 42 38 38 14 10]


In [38]:
w1=np.array([[1,2,7],[3,4,-8],[5,6,0]])
print(w1)
print(w1.ndim)

[[ 1  2  7]
 [ 3  4 -8]
 [ 5  6  0]]
2


In [39]:
print(np.where(w1%2==0))
print(w1[np.where(w1%2==0)])

(array([0, 1, 1, 2, 2], dtype=int64), array([1, 1, 2, 1, 2], dtype=int64))
[ 2  4 -8  6  0]


In [40]:
# 6 np.extract()

print(p1)
t1=np.extract(p1>20,p1)
print(t1)
t2=np.extract(p1%3!=0,p1)
print(t2)

[12 14  7 79 32 45 28  4 17]
[79 32 45 28]
[14  7 79 32 28  4 17]


In [41]:
w1=np.array([[1,2,7],[3,4,8],[5,6,13]])
print(w1)
print(w1.ndim)

[[ 1  2  7]
 [ 3  4  8]
 [ 5  6 13]]
2


In [42]:
res=np.extract(w1%2==0,w1)
print(res)

[2 4 8 6]
