In [4]:
# 1  write a numpy program to generate six random integers between 10 and 30
import numpy as np

In [7]:
x=np.random.randint(low=10,high=30,size=6)
print(x)

[29 22 24 25 15 29]


In [9]:
# 2 write a numpy program to create a 3x3 matrix with value ranging from 20 to 28

import numpy as np
x=np.arange(20,29).reshape(3,3)
print(x)

[[20 21 22]
 [23 24 25]
 [26 27 28]]


In [ ]:
# 3 write a numpy programe to create a vector filled with 1s of size 10 and update
# the sixth value to 25
