In [2]:
# ARRAY INDEXING

import numpy as np

In [5]:
a=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,])
print(a)
print(len(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
14
1
(14,)
14
int32


In [5]:
# indexing in 1d array
print(a)
print(a[0])
print(a[4])
print(a[8])
print(a[-2])
print(a[-7])
print(a[-5])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
12
16
20
24
19
21


In [7]:
#1D SLICING

print(a)
print(a[2:5])
print(a[3:])
print(a[:6])
print(a[-4:])
print(a[:-6])
print(a[:])


[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[14 15 16]
[15 16 17 18 19 20 21 22 23 24 25]
[12 13 14 15 16 17]
[22 23 24 25]
[12 13 14 15 16 17 18 19]
[12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [10]:
print(a)
print(a[1:8:2])
print(a[3:-7])
print(a[3:-7:2])
print(a[-2:-8:-2])
print(a[-2:3:-3])
print(a[3:13:3])


[12 13 14 15 16 17 18 19 20 21 22 23 24 25]
[13 15 17 19]
[15 16 17 18]
[15 17]
[24 22 20]
[24 21 18]
[15 18 21 24]


In [11]:
# 2D ARRAY

import numpy as np

In [14]:
b=np.array([[31,32,33,34],[35,36,37,38],
           [39,40,41,42],[43,44,45,46]])
print(b)
print(b.ndim)
nt(print(b.shape)
print(b.size)
print(b.dtype)

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]
2
(4, 4)
16
int32


In [21]:
# 2D INDEXING

print(b)


[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]


In [22]:
#2D SLICING

print(b)

[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]]


In [23]:
print(b[-1])
print(b[:-1])
print(b[:,-1])
print(b[-2,:-2])


[43 44 45 46]
[[31 32 33 34]
 [35 36 37 38]
 [39 40 41 42]]
[34 38 42 46]
[39 40]


In [24]:
print(b[1:,3:]) # start_row=1,step row=1,start col=3,step col= +1

[[38]
 [42]
 [46]]


In [25]:
print(b[-2:,:-1])
print(b[1:,2:])
print(b[:2,0:])
print(b[::2,:])

[[39 40 41]
 [43 44 45]]
[[37 38]
 [41 42]
 [45 46]]
[[31 32 33 34]
 [35 36 37 38]]
[[31 32 33 34]
 [39 40 41 42]]


In [26]:
print(b[:2,::2])

[[31 33]
 [35 37]]


In [28]:
print(b[1::2,1::2])
print(b[0::2,0::3])
print(b[-3::-1,-3])

[[36 38]
 [44 46]]
[[31 34]
 [39 42]]
[36 32]


In [29]:
print(b[:2:-1,2::])
print(b[:1:-1,:3])
print(b[0::3,0::3])
print(b[-1::-3,-1::-3])

[[45 46]]
[[43 44 45]
 [39 40 41]]
[[31 34]
 [43 46]]
[[46 43]
 [34 31]]


In [30]:
print(b[1:3,1:3])
print(b[-2:-4:-1,-1::-3])
print(b[-2::-2,-2:-4:-1])
print(b[-2::-2,-2:0:-1])

[[36 37]
 [40 41]]
[[42 39]
 [38 35]]
[[41 40]
 [33 32]]
[[41 40]
 [33 32]]


In [31]:
# 2D ADVANCED INDEXING AND SLICING


print(b[[0,1,2],[0,1,2]])
print(b[[0,1,2,3,0,3],[0,1,2,3,2,2,]])
print(b[[0,1,2,3],[3,2,1,0]])
print(b[[1,2,-1,-2],[0,1,-2,-4]])

[31 36 41]
[31 36 41 46 33 45]
[34 37 40 43]
[35 40 45 39]


In [33]:
#3D ARRAY indexing

a=np.arange(32).reshape(2,4,4)
print(a)
print(a.dtype)
print(a.shape)
print(a.size)
print(a.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
int32
(2, 4, 4)
32
3


In [35]:
print(a[-2])
print(a[-1][-2])
print(a[-1][-2][-3])
print([--1,2,2])
print(a[-2][0][-1])
print(a[1,3,2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[24 25 26 27]
25
[1, 2, 2]
3
30


In [37]:
# 3D slicing

print(a[1:,1:,2:])
print(a[1:,:2,:2])
print(a[0:1,3:,1:])

[[[22 23]
  [26 27]
  [30 31]]]
[[[16 17]
  [20 21]]]
[[[13 14 15]]]


In [38]:
print(a[0:,1::2,:2])

[[[ 4  5]
  [12 13]]

 [[20 21]
  [28 29]]]


In [39]:
print(a[-1:,:,:])
print(a[:-1,:,:])

[[[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]


In [40]:
print(a[-2:,-2::-2,-1::-2])
print(a[-2:,-1::-3,-1::-2])

[[[11  9]
  [ 3  1]]

 [[27 25]
  [19 17]]]
[[[15 13]
  [ 3  1]]

 [[31 29]
  [19 17]]]


In [41]:
print(a[-2:,-1::-2,1:3])
print(a[:,::3,::2])
print(a[-2::,-4::3,-3::2])
print(a[-2::,-3:-1,1])

[[[13 14]
  [ 5  6]]

 [[29 30]
  [21 22]]]
[[[ 0  2]
  [12 14]]

 [[16 18]
  [28 30]]]
[[[ 1  3]
  [13 15]]

 [[17 19]
  [29 31]]]
[[ 5  9]
 [21 25]]


In [42]:
print(a[::-1,-2:-4:-1,-1::-2])

[[[27 25]
  [23 21]]

 [[11  9]
  [ 7  5]]]


In [43]:
print(a[::-1,-1::-3,-2:-4:-1])

[[[30 29]
  [18 17]]

 [[14 13]
  [ 2  1]]]


In [45]:
#3D ADVANCED INDEXING SLICING

print(a[[0,0,0,0,],[1,0,2,3,],[1,3,1,2]])
print(a[[0,1,0,1],[1,2,3,0],[2,0,1,2]])
print(a[[0,0,0,0,1],[0,1,2,3,2],[0,1,2,2,1]])

[ 5  3  9 14]
[ 6 24 13 18]
[ 0  5 10 14 25]
