In [ ]:
# solving linear algebra
# 2x+3y=20
#5x-4y=27

In [1]:
import numpy as np

In [2]:
a=np.array([[2,3],[5,-4]]) #[2x+3y][5x-4y]
b=np.array([20,27])        #[20,27]
res=np.linalg.solve(a,b)
print(res)

[7. 2.]


In [3]:
# solving linear equation with 3 unknown and 3 equation

# 8x+3y-2z=9
#-4x+7y+5z=15
#3x+4y-12z=35

a=np.array([[8,3,-2],[-4,7,5],[3,4,-12]])
b=np.array([9,15,35])
x=np.linalg.solve(a,b)
print(x)

[-0.58226371  3.22870478 -1.98599767]


In [9]:
# Dot product

a=np.array([[9,5,2],[1,8,5],[3,1,6]])
print(a.shape)
print(a)



(3, 3)
[[9 5 2]
 [1 8 5]
 [3 1 6]]


In [5]:
b=np.array([[3,2],[1,4],[5,3]])
print(b.shape)

(3, 2)


In [8]:
res1=np.dot(a,b)
res2=np.matmul(a,b)
print(res1)
print(res1.shape)
print(res2)
print(res2.shape)

[[42 44]
 [36 49]
 [40 28]]
(3, 2)
[[42 44]
 [36 49]
 [40 28]]
(3, 2)


In [15]:
# matrix inverse

q=np.array([[2,3],[1,2]])
print(q)
print(q.shape)

[[2 3]
 [1 2]]
(2, 2)


In [16]:
q_inv=np.linalg.inv(q)
print(q_inv)

[[ 2. -3.]
 [-1.  2.]]


In [17]:
r1=np.dot(q,q_inv)
print(r1)

[[1. 0.]
 [0. 1.]]


In [20]:
w=np.array([[5,3],[2,4]])
print(w) #5*4-2*3=20-6=14
det=np.linalg.det(w)
print('det of w is',round(det))

[[5 3]
 [2 4]]
det of w is 14


In [25]:
a=np.array([[30,31,40],[41,50,51],[60,61,70]])
print(np.linalg.det(a))

-2399.999999999998


In [26]:
a=np.array([[20,10],[50,10]])
print("\ntrace of a:",np.trace(a))


trace of a: 30


In [27]:
a=np.array([[-3,2,-5],[2,-3,4],[1,1,1]])
b=np.array([[3,2],[1,4],[5,3]])
c=np.dot(a,b)
c.shape

(3, 2)

In [28]:
a=np.array([[2,3],[5,-4]])
b=np.array([20,27])
res=np.linalg.solve(a,b)
print(res)

[7. 2.]


In [29]:
a=np.array([[55,5],[35,15]])
eig_val,eig_vec=np.linalg.eig(a)
print('eigen values\n',eig_val)
print('eigen vector\n',eig_vec)

eigen values
 [58.97915762 11.02084238]
eigen vector
 [[ 0.78245733 -0.11296251]
 [ 0.62270421  0.99359925]]


In [30]:
a=np.array([[1,2],[3,4]])
print(np.linalg.det(a))

-2.0000000000000004


In [21]:
# trace: primary diagonal element

a=np.array([[3,6,2],[9,12,17],[22,18,15]])
print(a)
trace=np.trace(a)
print('trace of a is',trace)

[[ 3  6  2]
 [ 9 12 17]
 [22 18 15]]
trace of a is 30


In [23]:
# eigen values and eigen vector
 
d=np.array([[7,4],[5,9]])
print(d)
print(d.shape)


[[7 4]
 [5 9]]
(2, 2)


In [24]:
eig_val,eig_vec=np.linalg.eig(d)
print('eigen vlues\n',eig_val)
print('eigen vector\n',eig_vec)

eigen vlues
 [ 3.41742431 12.58257569]
eigen vector
 [[-0.74490545 -0.58243756]
 [ 0.66717004 -0.81287544]]
