In [2]:
import numpy as np
#np is the alias name 

In [4]:
a1=np.array([3,4,5.7,8])
print(a1)

[3.  4.  5.7 8. ]


In [7]:
a2=np.array(['hello',4,5.7,8])
print(a2)
print(a2.dtype)

['hello' '4' '5.7' '8']
<U32


In [11]:
# numpy broadcasting

a=np.array([3,4,5,6,7])
b=np.array(2)
print('a',a,'dim',a.ndim)
print('b',b,'dim',b.ndim)
print(a*b)

a [3 4 5 6 7] dim 1
b 2 dim 0
[ 6  8 10 12 14]


In [4]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([-1,0,1])
print('a\n',a,'dim',a.ndim)
print('b\n',b,'dim',b.ndim)
print('a*b\n',a*b)

a
 [[1 2 3]
 [4 5 6]] dim 2
b
 [-1  0  1] dim 1
a*b
 [[-1  0  3]
 [-4  0  6]]


In [5]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[5,-4,2],[-2,3,-1]])
print('a\n',a,'dim',a.ndim)
print('b\n',b,'dim',b.ndim)
print('a*b\n',a*b)

a
 [[1 2 3]
 [4 5 6]] dim 2
b
 [[ 5 -4  2]
 [-2  3 -1]] dim 2
a*b
 [[ 5 -8  6]
 [-8 15 -6]]


In [7]:
# np.linspace()

z1=np.linspace(2,10,5)
print(z1)
z2=np.linspace(2,10,3,dtype='int')
print(z2)
s1=np.linspace(5,20,7)
print(s1)
s1=np.linspace(5,20,7,dtype=int)
print(s1)

[ 2.  4.  6.  8. 10.]
[ 2  6 10]
[ 5.   7.5 10.  12.5 15.  17.5 20. ]
[ 5  7 10 12 15 17 20]


In [8]:
z1=np.linspace(4,17,6)
print(z1)

[ 4.   6.6  9.2 11.8 14.4 17. ]


In [9]:
z4=np.linspace(2,20)
print(z4)
print(type(z4))
print(len(z4))

[ 2.          2.36734694  2.73469388  3.10204082  3.46938776  3.83673469
  4.20408163  4.57142857  4.93877551  5.30612245  5.67346939  6.04081633
  6.40816327  6.7755102   7.14285714  7.51020408  7.87755102  8.24489796
  8.6122449   8.97959184  9.34693878  9.71428571 10.08163265 10.44897959
 10.81632653 11.18367347 11.55102041 11.91836735 12.28571429 12.65306122
 13.02040816 13.3877551  13.75510204 14.12244898 14.48979592 14.85714286
 15.2244898  15.59183673 15.95918367 16.32653061 16.69387755 17.06122449
 17.42857143 17.79591837 18.16326531 18.53061224 18.89795918 19.26530612
 19.63265306 20.        ]
<class 'numpy.ndarray'>
50


In [3]:
w = np.linsapce(5,20,7,retstep=True)
print(w)

AttributeError: module 'numpy' has no attribute 'linsapce'

In [13]:
# view vs copy
a1=np.array([1,2,3,4,5])
x=a1.copy()
print('a1\n',a1,'shape',a1.shape)
print('x\n',x)
a1[0]=50
print('a1\n',a1)
print('x\n',x)

a1
 [1 2 3 4 5] shape (5,)
x
 [1 2 3 4 5]
a1
 [50  2  3  4  5]
x
 [1 2 3 4 5]


In [14]:
a2=np.array([1,2,3,4,5])
y=a2.view()
print('a1\n',a2)
print('y\n',y)
a2[0]=50
print('a2\n',a2)
print('y\n',y)

a1
 [1 2 3 4 5]
y
 [1 2 3 4 5]
a2
 [50  2  3  4  5]
y
 [50  2  3  4  5]


In [16]:
 #1. numpy random numbers
a1=np.random.random(5)
print(a1)
a2=np.random.random((3,4))
print(a2)

[0.42450187 0.87420266 0.30061072 0.14114609 0.37358111]
[[0.81150283 0.47852156 0.76480117 0.87501742]
 [0.93309161 0.18560243 0.1536424  0.28419436]
 [0.25597233 0.84319573 0.26896404 0.04628089]]


In [20]:
#2.p.random.randint

a3=np.random.randint( 3,15,4)
print(a3)
a4=np.random.randint(50,100,8)
print(a4)
a5=np.random.randint(20,5,4)# error low /high
print(a5)

[10 12 10  5]
[82 61 81 63 69 79 51 53]


ValueError: low >= high

In [22]:
a5=np.random.randint(10,50,(3,4))
print(a5)

[[30 23 31 37]
 [37 46 18 31]
 [29 30 30 39]]


In [24]:
# 3.np.random.rand()
w1=np.random.rand(5)
print(w1)
w2=np.random.rand(4,2)
print(w2)
w3=np.random.random((4,2))
print(w3)

[0.84714064 0.77570638 0.82923035 0.48112431 0.23917525]
[[0.72591254 0.98566268]
 [0.662668   0.0903603 ]
 [0.58460226 0.56024066]
 [0.62648299 0.89104086]]
[[0.48253877 0.49717966]
 [0.4112882  0.06894522]
 [0.53994393 0.47784895]
 [0.9994031  0.70708836]]


In [27]:
#4. np.random.choice

w1=np.random.choice([3,9,15,6,7,8],size=4)
print(w1)

[6 3 6 7]


In [28]:
w2=np.random.choice([3,9,15,6,7,8,13,15,11,12,10],size=4)
print(w2)

[ 7  9 11  8]
